name: rook
channels:
- conda-forge
- defaults
dependencies:
- pip
- python=3.7 # >=3.6,<3.8
- pywps>=4.5.2,<4.6
- jinja2
- click
- psutil
- requests
# daops
- cftime>=1.2.1
- xarray>=0.20
- dask>=2021.12
- netcdf4>=1.4
- bottleneck>=1.3.1,<1.4
- daops>=0.8.1,<0.9
- clisops>=0.9.2,<0.10
- roocs-utils>=0.6.2,<0.7
# workflow
- networkx
# provenance
- prov>=2.0.0
- pydot
- graphviz
# catalog
- intake
- pandas>=1.3.5,<1.4
- aiohttp
# dashboard
- bokeh>=2.4.2,<2.5
# tests
- pytest
