name: rook
channels:
- conda-forge
- defaults
dependencies:
- pip
- python=3.7 # >=3.6,<3.8
- pywps>=4.4.0,<4.5
- jinja2
- click
- psutil
# tests
- pytest
- cftime>=1.2.1
- xarray>=0.16
- dask>=2.26
- netcdf4>=1.4
# - daops>=0.4.0,<0.5
- clisops>=0.6.1,<0.7
- roocs-utils>=0.2.1,<0.3
# workflow
- networkx
# provenance
- prov>=2.0.0
- graphviz
- pip:
    - daops @ git+https://github.com/roocs/daops.git@add_average#egg=daops
