name: rook
channels:
  - conda-forge
dependencies:
  - python >=3.10,<3.14
  - pywps >=4.5.2,<4.8
  - jinja2 >=3.1.4
  - click >=8.1.7
  - psutil >=6.0.0
  - requests
  - cftime >=1.2.1
  - xarray >=2025.1.1 
  - xesmf >=0.8.2
  - cf_xarray >=0.7
  - dask >=2021.12
  - netcdf4 >=1.4
  - daops >=0.15.0
  - clisops >=0.17.0
  - h5netcdf
  - roocs-grids >=0.1.2
  - beautifulsoup4 >4.12.3
  # workflow
  - networkx
  # provenance
  - prov >=2.0.0
  - pydot
  - graphviz
  # catalog
  - intake <2.0
  - pandas >=2.0
  - sqlalchemy >=2.0
  - aiohttp
  # dashboard
  - bokeh >= 3.7.0
  - humanize
