name: rook
channels:
- conda-forge
- defaults
dependencies:
- pip
- python>=3.9
- pywps>=4.5.2,<4.7
- jinja2
- click
- psutil
- requests
# daops
- cftime>=1.2.1
- xarray >=0.21,<2023.3.0 # https://github.com/pydata/xarray/issues/7794
- xesmf >=0.8.2
- cf_xarray>=0.7
- dask>=2021.12
- netcdf4>=1.4
- bottleneck>=1.3.1,<1.4
#- daops>=0.9.0,<0.10
#- clisops>=0.12.0,<0.13
- roocs-utils>=0.6.4,<0.7
# workflow
- networkx
# provenance
- prov>=2.0.0
- pydot
- graphviz
# catalog
- intake
- pandas>=1.3.5,<1.4
- sqlalchemy>=1.4.45,<2.0
- aiohttp
# dashboard
- bokeh>=2.4.2,<2.5
# tests
- pytest
