name: rook
channels:
- conda-forge
- defaults
dependencies:
#- python=3.7
- pip
- python>=3.6,<3.8
- pywps>=4.2.7,<4.3
- jinja2
- click
- psutil
# tests
- pytest
# daops
- rtree>=0.9
- cfunits
- cftime>=1.2.1
- udunits2>=2.2
- xarray>=0.15
- dask
- netcdf4
# - clisops>=0.3.0,<0.4
# workflow
- networkx
# tests
- pytest
- pip:
  # - daops>=0.2.0<0.3
  - -e git+https://github.com/roocs/roocs-utils.git@master#egg=roocs_utils
  - -e git+https://github.com/roocs/clisops.git@master#egg=clisops
  - -e git+https://github.com/roocs/daops.git@master#egg=daops
